# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internship.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10internship.proto\x12\ninternship\"\\\n\nInternship\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0c\n\x04link\x18\x04 \x01(\t\x12\x0c\n\x04\x61rea\x18\x05 \x01(\t\"Q\n\x12InternshipCategory\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12)\n\tpositions\x18\x02 \x03(\x0b\x32\x16.internship.Internship\"\x17\n\x15GetInternshipsRequest\"L\n\x16GetInternshipsResponse\x12\x32\n\ncategories\x18\x01 \x03(\x0b\x32\x1e.internship.InternshipCategory2n\n\x11InternshipService\x12Y\n\x0eGetInternships\x12!.internship.GetInternshipsRequest\x1a\".internship.GetInternshipsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'internship_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INTERNSHIP']._serialized_start=32
  _globals['_INTERNSHIP']._serialized_end=124
  _globals['_INTERNSHIPCATEGORY']._serialized_start=126
  _globals['_INTERNSHIPCATEGORY']._serialized_end=207
  _globals['_GETINTERNSHIPSREQUEST']._serialized_start=209
  _globals['_GETINTERNSHIPSREQUEST']._serialized_end=232
  _globals['_GETINTERNSHIPSRESPONSE']._serialized_start=234
  _globals['_GETINTERNSHIPSRESPONSE']._serialized_end=310
  _globals['_INTERNSHIPSERVICE']._serialized_start=312
  _globals['_INTERNSHIPSERVICE']._serialized_end=422
# @@protoc_insertion_point(module_scope)
