# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import internship_pb2 as internship__pb2


class InternshipServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInternships = channel.unary_unary(
                '/internship.InternshipService/GetInternships',
                request_serializer=internship__pb2.GetInternshipsRequest.SerializeToString,
                response_deserializer=internship__pb2.GetInternshipsResponse.FromString,
                )


class InternshipServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInternships(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternshipServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInternships': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInternships,
                    request_deserializer=internship__pb2.GetInternshipsRequest.FromString,
                    response_serializer=internship__pb2.GetInternshipsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'internship.InternshipService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InternshipService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInternships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/internship.InternshipService/GetInternships',
            internship__pb2.GetInternshipsRequest.SerializeToString,
            internship__pb2.GetInternshipsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
